=== Repiteo/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?><!-- dummy -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" use="optional" />
			<xs:attribute type="xs:string" name="api_type" use="optional" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Repiteo/godot/doc/classes/GDExtensionManager.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="GDExtensionManager" inherits="Object" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Provides access to GDExtension functionality.
	</brief_description>
	<description>
		The GDExtensionManager loads, initializes, and keeps track of all available [GDExtension] libraries in the project.
		[b]Note:[/b] Do not worry about GDExtension unless you know what you are doing.
	</description>
	<tutorials>
		<link title="GDExtension overview">$DOCS_URL/engine_details/engine_api/gdextension/what_is_gdextension.html</link>
		<link title="GDExtension example in C++">$DOCS_URL/tutorials/scripting/cpp/gdextension_cpp_example.html</link>
	</tutorials>
	<methods>
		<method name="get_extension">
			<return type="GDExtension" />
			<param index="0" name="path" type="String" />
			<description>
				Returns the [GDExtension] at the given file [param path], or [code]null[/code] if it has not been loaded or does not exist.
			</description>
		</method>
		<method name="get_loaded_extensions" qualifiers="const">
			<return type="PackedStringArray" />
			<description>
				Returns the file paths of all currently loaded extensions.
			</description>
		</method>
		<method name="is_extension_loaded" qualifiers="const">
			<return type="bool" />
			<param index="0" name="path" type="String" />
			<description>
				Returns [code]true[/code] if the extension at the given file [param path] has already been loaded successfully. See also [method get_loaded_extensions].
			</description>
		</method>
		<method name="load_extension">
			<return type="int" enum="GDExtensionManager.LoadStatus" />
			<param index="0" name="path" type="String" />
			<description>
				Loads an extension by absolute file path. The [param path] needs to point to a valid [GDExtension]. Returns [constant LOAD_STATUS_OK] if successful.
			</description>
		</method>
		<method name="load_extension_from_function">
			<return type="int" enum="GDExtensionManager.LoadStatus" />
			<param index="0" name="path" type="String" />
			<param index="1" name="init_func" type="const char(void (__cdecl *(__cdecl *)(const char *))(void),void *,GDExtensionInitialization *) **" />
			<description>
				Loads the extension already in address space via the given path and initialization function. The [param path] needs to be unique and start with [code]"libgodot://"[/code]. Returns [constant LOAD_STATUS_OK] if successful.
			</description>
		</method>
		<method name="reload_extension">
			<return type="int" enum="GDExtensionManager.LoadStatus" />
			<param index="0" name="path" type="String" />
			<description>
				Reloads the extension at the given file path. The [param path] needs to point to a valid [GDExtension], otherwise this method may return either [constant LOAD_STATUS_NOT_LOADED] or [constant LOAD_STATUS_FAILED].
				[b]Note:[/b] You can only reload extensions in the editor. In release builds, this method always fails and returns [constant LOAD_STATUS_FAILED].
			</description>
		</method>
		<method name="unload_extension">
			<return type="int" enum="GDExtensionManager.LoadStatus" />
			<param index="0" name="path" type="String" />
			<description>
				Unloads an extension by file path. The [param path] needs to point to an already loaded [GDExtension], otherwise this method returns [constant LOAD_STATUS_NOT_LOADED].
			</description>
		</method>
	</methods>
	<signals>
		<signal name="extension_loaded">
			<param index="0" name="extension" type="GDExtension" />
			<description>
				Emitted after the editor has finished loading a new extension.
				[b]Note:[/b] This signal is only emitted in editor builds.
			</description>
		</signal>
		<signal name="extension_unloading">
			<param index="0" name="extension" type="GDExtension" />
			<description>
				Emitted before the editor starts unloading an extension.
				[b]Note:[/b] This signal is only emitted in editor builds.
			</description>
		</signal>
		<signal name="extensions_reloaded">
			<description>
				Emitted after the editor has finished reloading one or more extensions.
			</description>
		</signal>
	</signals>
	<constants>
		<constant name="LOAD_STATUS_OK" value="0" enum="LoadStatus">
			The extension has loaded successfully.
		</constant>
		<constant name="LOAD_STATUS_FAILED" value="1" enum="LoadStatus">
			The extension has failed to load, possibly because it does not exist or has missing dependencies.
		</constant>
		<constant name="LOAD_STATUS_ALREADY_LOADED" value="2" enum="LoadStatus">
			The extension has already been loaded.
		</constant>
		<constant name="LOAD_STATUS_NOT_LOADED" value="3" enum="LoadStatus">
			The extension has not been loaded.
		</constant>
		<constant name="LOAD_STATUS_NEEDS_RESTART" value="4" enum="LoadStatus">
			The extension requires the application to restart to fully load.
		</constant>
	</constants>
</class>

=== Repiteo/godot/doc/classes/TypeRef.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="TypeRef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<constructors>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="from" type="TypeRef" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="type_struct" type="Array" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="variant_type" type="int" />
			<param index="1" name="class_name" type="StringName" />
			<param index="2" name="script" type="Variant" />
			<param index="3" name="nested_types" type="Array" />
			<description>
			</description>
		</constructor>
	</constructors>
	<methods>
		<method name="from_builtin_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="variant_type" type="int" />
			<description>
			</description>
		</method>
		<method name="from_native_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="class_name" type="StringName" />
			<description>
			</description>
		</method>
		<method name="from_script_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="script" type="Variant" />
			<description>
			</description>
		</method>
		<method name="get_builtin_type" qualifiers="const">
			<return type="int" />
			<description>
			</description>
		</method>
		<method name="get_native_type" qualifiers="const">
			<return type="StringName" />
			<description>
			</description>
		</method>
		<method name="get_nested_types" qualifiers="const">
			<return type="Array" />
			<description>
			</description>
		</method>
		<method name="get_script_type" qualifiers="const">
			<return type="Variant" />
			<description>
			</description>
		</method>
		<method name="has_nested_types" qualifiers="const">
			<return type="bool" />
			<description>
			</description>
		</method>
		<method name="hash" qualifiers="const">
			<return type="int" />
			<description>
			</description>
		</method>
	</methods>
</class>

=== Repiteo/godot/doc/classes/PhysicsDirectSpaceState2DExtension.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="PhysicsDirectSpaceState2DExtension" inherits="PhysicsDirectSpaceState2D" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Provides virtual methods that can be overridden to create custom [PhysicsDirectSpaceState2D] implementations.
	</brief_description>
	<description>
		This class extends [PhysicsDirectSpaceState2D] by providing additional virtual methods that can be overridden. When these methods are overridden, they will be called instead of the internal methods of the physics server.
		Intended for use with GDExtension to create custom implementations of [PhysicsDirectSpaceState2D].
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="_cast_motion" qualifiers="virtual required">
			<return type="bool" />
			<param index="0" name="shape_rid" type="RID" />
			<param index="1" name="transform" type="Transform2D" />
			<param index="2" name="motion" type="Vector2" />
			<param index="3" name="margin" type="float" />
			<param index="4" name="collision_mask" type="int" />
			<param index="5" name="collide_with_bodies" type="bool" />
			<param index="6" name="collide_with_areas" type="bool" />
			<param index="7" name="r_closest_safe" type="float*" />
			<param index="8" name="r_closest_unsafe" type="float*" />
			<description>
			</description>
		</method>
		<method name="_collide_shape" qualifiers="virtual required">
			<return type="bool" />
			<param index="0" name="shape_rid" type="RID" />
			<param index="1" name="transform" type="Transform2D" />
			<param index="2" name="motion" type="Vector2" />
			<param index="3" name="margin" type="float" />
			<param index="4" name="collision_mask" type="int" />
			<param index="5" name="collide_with_bodies" type="bool" />
			<param index="6" name="collide_with_areas" type="bool" />
			<param index="7" name="r_results" type="Vector2*" />
			<param index="8" name="max_results" type="int" />
			<param index="9" name="r_result_count" type="int32_t*" />
			<description>
			</description>
		</method>
		<method name="_intersect_point" qualifiers="virtual required">
			<return type="int" />
			<param index="0" name="position" type="Vector2" />
			<param index="1" name="canvas_instance_id" type="int" />
			<param index="2" name="collision_mask" type="int" />
			<param index="3" name="collide_with_bodies" type="bool" />
			<param index="4" name="collide_with_areas" type="bool" />
			<param index="5" name="r_results" type="PhysicsServer2DExtensionShapeResult*" />
			<param index="6" name="max_results" type="int" />
			<description>
			</description>
		</method>
		<method name="_intersect_ray" qualifiers="virtual required">
			<return type="bool" />
			<param index="0" name="from" type="Vector2" />
			<param index="1" name="to" type="Vector2" />
			<param index="2" name="collision_mask" type="int" />
			<param index="3" name="collide_with_bodies" type="bool" />
			<param index="4" name="collide_with_areas" type="bool" />
			<param index="5" name="hit_from_inside" type="bool" />
			<param index="6" name="r_result" type="PhysicsServer2DExtensionRayResult*" />
			<description>
			</description>
		</method>
		<method name="_intersect_shape" qualifiers="virtual required">
			<return type="int" />
			<param index="0" name="shape_rid" type="RID" />
			<param index="1" name="transform" type="Transform2D" />
			<param index="2" name="motion" type="Vector2" />
			<param index="3" name="margin" type="float" />
			<param index="4" name="collision_mask" type="int" />
			<param index="5" name="collide_with_bodies" type="bool" />
			<param index="6" name="collide_with_areas" type="bool" />
			<param index="7" name="r_result" type="PhysicsServer2DExtensionShapeResult*" />
			<param index="8" name="max_results" type="int" />
			<description>
			</description>
		</method>
		<method name="_rest_info" qualifiers="virtual required">
			<return type="bool" />
			<param index="0" name="shape_rid" type="RID" />
			<param index="1" name="transform" type="Transform2D" />
			<param index="2" name="motion" type="Vector2" />
			<param index="3" name="margin" type="float" />
			<param index="4" name="collision_mask" type="int" />
			<param index="5" name="collide_with_bodies" type="bool" />
			<param index="6" name="collide_with_areas" type="bool" />
			<param index="7" name="r_rest_info" type="PhysicsServer2DExtensionShapeRestInfo*" />
			<description>
			</description>
		</method>
		<method name="is_body_excluded_from_query" qualifiers="const">
			<return type="bool" />
			<param index="0" name="body" type="RID" />
			<description>
			</description>
		</method>
	</methods>
</class>
